import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import FileInput from './components/FileInput'
import { AmplifySignOut } from "@aws-amplify/ui-react"

import MainNavbar from './components/MainNavbar'


export default function Home() {
  return (
    
    <div className={styles.container}>
      <MainNavbar/>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"/>
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          GTRI Analysis of Extremist Behavior Dashboard
        </h1>

        <p className={styles.description}>
          Get started by inputing a{' '}
          <code className={styles.code}>file</code>
          .
        </p>
        
        {/* <FileInput/> */}
        <div className={styles.grid}>
          {/* will be a link to the new page */}
          {/* <a href="https://nextjs.org/docs" className={styles.card}> */}
          <a href="" className={styles.card}>
            <h2>Upload New Data &rarr;</h2>
            <p>Analyze new sources of data using our persuasion detection algorithm.</p>
          </a>

          <a href="" className={styles.card}>
            <h2>Analyze Existing Data &rarr;</h2>
            <p>Review existing sources of data by accessing your past uploads.</p>
          </a>

          {/* <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={styles.card}
          >
             <h2> &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a> */}

        </div>
        
      </main>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
